Icky 177
Kibo-UCP/vercel-commerce pull request #13
Opened 2021-09-03 12:06 UTC by kibo-chandradeeptalaha

Remove item from cart implemented

2021-09-03 17:20 UTC, kibo-kevinwatts requested changes

2021-09-03 17:20 UTC, kibo-kevinwatts commented on framework/kibocommerce/api/endpoints/cart/remove-item.ts
> +    debugger
remove debugger statement

2021-09-06 04:57 UTC, kibo-chandradeeptalaha commented on framework/kibocommerce/api/endpoints/cart/remove-item.ts
> +    debugger
Removed

2021-09-08 16:48 UTC, kibo-kevinwatts approved these changes

2021-09-08 16:48 UTC, merged