Feature/icky- 180 & 181
Kibo-UCP/vercel-commerce pull request #20
Opened 2021-09-14 09:29 UTC by kibo-geetanshuchhabra

2021-09-15 20:00 UTC, kibo-kevinwatts requested changes

2021-09-15 20:00 UTC, kibo-kevinwatts commented on framework/kibocommerce/api/endpoints/wishlist/add-item.ts
> +import addItemToWishlist from '../../mutations/addItemToWishlist-mutation'
Rename `addItemToWishlist` to `addItemToWishlistMutation`

2021-09-15 20:00 UTC, kibo-kevinwatts commented on framework/kibocommerce/api/endpoints/wishlist/remove-item.ts
> +import removeItemFromWishlist from '../../mutations/removeItemFromWishlist-mutation'
Rename `removeItemFromWishlist` to `removeItemFromWishlistMutation`

2021-09-16 06:47 UTC, kibo-geetanshuchhabra commented on framework/kibocommerce/api/endpoints/wishlist/add-item.ts
> +import addItemToWishlist from '../../mutations/addItemToWishlist-mutation'
Resolved

2021-09-16 06:47 UTC, kibo-geetanshuchhabra commented on framework/kibocommerce/api/endpoints/wishlist/remove-item.ts
> +import removeItemFromWishlist from '../../mutations/removeItemFromWishlist-mutation'
Resolved

2021-09-16 23:52 UTC, merged