Fix/icky 276
Kibo-UCP/vercel-commerce pull request #21
Opened 2021-09-28 11:24 UTC by kibo-chandradeeptalaha

2021-10-01 17:03 UTC, kibo-kevinwatts requested changes

2021-10-01 17:03 UTC, kibo-kevinwatts commented on framework/kibocommerce/api/endpoints/customer/customer.ts
> +  debugger
remove the debugger statement

2021-10-01 17:03 UTC, kibo-kevinwatts commented on framework/kibocommerce/api/endpoints/customer/customer.ts
> +  const cookieHandlerResponse = await cookieHandler(config, req, res)
This doesn't need to be async

2021-10-04 08:06 UTC, kibo-chandradeeptalaha commented on framework/kibocommerce/api/endpoints/customer/customer.ts
> +  const cookieHandlerResponse = await cookieHandler(config, req, res)
Resolved all the points

2021-10-04 21:18 UTC, kibo-kevinwatts approved these changes

2021-10-04 21:19 UTC, merged