ICKY-263
Kibo-UCP/vercel-commerce pull request #23
Opened 2021-09-30 06:24 UTC by kibo-geetanshuchhabra

ICKY-263: Vercel Storefront My Profile: Email Address is not showing

2021-10-01 17:13 UTC, kibo-kevinwatts commented on framework/kibocommerce/lib/normalize.ts
> +export function normalizeCustomer(customer: any): any {
Add the Typescript param and return types

2021-10-01 17:13 UTC, kibo-kevinwatts requested changes
add typescript param/return type to normalize

2021-10-04 07:26 UTC, kibo-geetanshuchhabra commented on framework/kibocommerce/lib/normalize.ts
> +export function normalizeCustomer(customer: any): any {
Resolved

2021-10-04 21:27 UTC, kibo-kevinwatts approved these changes

2021-10-04 21:27 UTC, merged