Feature/icky 176
Kibo-UCP/vercel-commerce pull request #8
Opened 2021-09-01 14:44 UTC by kibo-chandradeeptalaha

2021-09-02 04:52 UTC, kibo-chandradeeptalaha commented on framework/kibocommerce/api/endpoints/cart/add-item.ts
> +      isAssemblyRequired: true,
Resolved

2021-09-02 20:24 UTC, kibo-kevinwatts requested changes

2021-09-02 20:24 UTC, kibo-kevinwatts commented on framework/kibocommerce/api/endpoints/cart/add-item.ts
> +  ).options[0].value
Update buildAddToCartVariables function to handle simple products ( no variantId and no variations )

2021-09-03 15:03 UTC, kibo-chandradeeptalaha commented on framework/kibocommerce/api/endpoints/cart/add-item.ts
> +  ).options[0].value
Resolved

2021-09-03 15:10 UTC, kibo-kevinwatts approved these changes

2021-09-03 15:11 UTC, merged